package common

const (
	// LiveSecretKeyRegex ...
	LiveSecretKeyRegex = `^sk_?(\w{8})-(\w{4})-(\w{4})-(\w{4})-(\w{12})$`
	// LivePublicKeyRegex ...
	LivePublicKeyRegex = `^pk_?(\w{8})-(\w{4})-(\w{4})-(\w{4})-(\w{12})$`
	// SandboxSecretKeyRegex ...
	SandboxSecretKeyRegex = `^sk_test_?(\w{8})-(\w{4})-(\w{4})-(\w{4})-(\w{12})$`
	// SandboxPublicKeyRegex ...
	SandboxPublicKeyRegex = `^pk_test_?(\w{8})-(\w{4})-(\w{4})-(\w{4})-(\w{12})$`
	FourKeyRegex          = `^(pk|sk)_(sbox_)?[a-z2-7]{26}[a-z2-7*#$=]$`
	FourOAuthJwtPattern   = `^([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_\-\+\/=]*)`
	// CardTokenRegex ...
	CardTokenRegex = `^(tok)_(\w{26})$`
	// SourceIDRegex ...
	SourceIDRegex = `^(src)_(\w{26})$`
)
